### ISSUE TITLE
AuthorizationError: Missing required parameter: response_type

### ISSUE THREAD

**Issue by andhikamaheva** [gerges-beshay/oauth2orize-examples#8]
I have an error when accessing `/dialog/authorize` after logged in.

the error message shown below

`AuthorizationError: Missing required parameter: response_type
    at /var/www/html/oauth2orize-examples/node_modules/oauth2orize/lib/middleware/authorization.js:120:46
    at pass (/var/www/html/oauth2orize-examples/node_modules/oauth2orize/lib/server.js:295:26)
    at pass (/var/www/html/oauth2orize-examples/node_modules/oauth2orize/lib/server.js:313:9)
    at pass (/var/www/html/oauth2orize-examples/node_modules/oauth2orize/lib/server.js:313:9)
    at Server._parse (/var/www/html/oauth2orize-examples/node_modules/oauth2orize/lib/server.js:318:5)
    at authorization (/var/www/html/oauth2orize-examples/node_modules/oauth2orize/lib/middleware/authorization.js:118:12)
    at Layer.handle [as handle_request] (/var/www/html/oauth2orize-examples/node_modules/express/lib/router/layer.js:95:5)
    at next (/var/www/html/oauth2orize-examples/node_modules/express/lib/router/route.js:137:13)
    at /var/www/html/oauth2orize-examples/node_modules/connect-ensure-login/lib/ensureLoggedIn.js:50:5
    at Layer.handle [as handle_request] (/var/www/html/oauth2orize-examples/node_modules/express/lib/router/layer.js:95:5)`

**Comment by w-site** [comment]
same issue
how you fix this?

**Comment by huangguozhen** [comment]
@andhikamaheva same issue.
how you fix this?

**Comment by lairoeaes** [comment]
Use `/dialog/authorize?response_type=code` in `authorizationURL`
